export type StorySection = { key: string; title: string; paragraphs: string[] };

export const storySections: StorySection[] = [
  {
    "key": "Prologue",
    "title": "The First Rule",
    "paragraphs": [
      "Aurelia Veyne had twenty-seven rules for time travel, although she often told her customers that there were only three because most people became nervous when they heard the full list.",
      "The first rule was simple:",
      "Never change an event that does not belong to you.",
      "The second rule was more specific:",
      "Never leave an object from the future in the past.",
      "A person could bring a personal object from the past into the future, and a future object could be carried into the past temporarily, but it had to return to its original time before the traveler came home.",
      "The third rule was the one most customers hated:",
      "Only two people can jump at the same time.",
      "“Are you sure you don’t have a fourth rule?” the man sitting inside the machine asked, trying to sound calm even though he had been holding his bag upside down for the past five minutes.",
      "Aurelia looked at him through the clear glass chamber.",
      "“I have twenty-seven rules,” she replied while tapping the control panel with one finger. “Twenty-eight if you count the rule that says customers are not allowed to panic inside the machine.”",
      "The man’s face immediately lost its color.",
      "“Twenty-seven?” he asked.",
      "“Twenty-eight,” Aurelia repeated, lifting one finger. “The extra rule is important because panicking customers usually touch buttons they should not touch, fall over, drop their belongings, or suddenly decide that they no longer want to travel through time after the machine has already started.”",
      "“I’m not panicking,” the man said, although his voice became noticeably higher.",
      "Aurelia pointed at his bag.",
      "“You are holding it upside down.”",
      "The man looked down.",
      "The zipper was open, and a small brown notebook was dangerously close to sliding onto the metal floor. He quickly turned the bag around and held it against his chest.",
      "Aurelia laughed, covering her mouth for a moment before returning her attention to the control panel. Her laughter was light and easy, the kind that appeared whenever she noticed something simple and ridiculous. Even in a room filled with dangerous machines and impossible calculations, she could still find humor in a man losing an argument with his own shoulder bag.",
      "She was sitting in front of the control table with one leg folded beneath her. Her straight black hair was tied into a messy ponytail, but several strands had fallen across her face. She pushed them behind her ear while reviewing the destination coordinates, occasionally squinting at the screen because she had forgotten to wear her glasses.",
      "The machine filled most of the underground room.",
      "Two large silver rings surrounded a clear glass chamber, each ring covered in small lights and narrow metal panels. Thick cables ran across the ceiling before disappearing into the walls, while smaller wires were secured along the floor with strips of black tape. Blue lights blinked around the safe walking area, showing Aurelia where no one was allowed to stand once the machine began its jump.",
      "To another person, the machine looked impossible.",
      "To Aurelia, it looked unfinished.",
      "She could still see the loose wiring near the right wall, the uneven metal plate beneath the control table, and the thin scratch near the left ring that she had been planning to repair for almost three months.",
      "“Your destination is June 14, 1998,” Aurelia said while checking the energy level of the chamber. “You will remain there for exactly forty-three minutes, and the machine will automatically return you to this room when the timer reaches zero.”",
      "The man nodded slowly.",
      "“I only want to see my father,” he said.",
      "“You may speak with him, ask questions, and tell him personal things,” Aurelia explained. “You may even tell him what year you came from, as long as you do not use that information to control his decisions or change an event that affects the future.”",
      "“I understand,” the man replied.",
      "“You cannot warn him about the accident,” Aurelia continued.",
      "The man looked down at the floor.",
      "Aurelia’s smile disappeared as she watched his fingers tighten around the strap of his bag.",
      "His name was Tomas Reyes. He was forty-nine years old, worked as a financial manager in Makati, and had paid a large amount of money for a single visit to the past. He had contacted Aurelia through someone she trusted, completed three interviews, signed several agreements, and accepted every rule before she allowed him near the machine.",
      "Tomas did not want to change his father’s life.",
      "He did not want to prevent the accident that would eventually take him away.",
      "He only wanted to meet him while he was still alive.",
      "He wanted to say goodbye to a man whose face had become unclear in his memory.",
      "Aurelia understood that kind of request more than she wanted to admit.",
      "She turned toward the control panel and adjusted the location coordinates.",
      "“Your father will be at a small restaurant in Quezon City,” Aurelia explained. “He will be thirty-two years old, wearing a green polo shirt, and sitting beside the window with a cup of black coffee.”",
      "Tomas closed his eyes.",
      "“I remember that shirt,” he said.",
      "“You were there?” Aurelia asked.",
      "“I was six,” Tomas answered. “I remember the color, but I don’t remember his face clearly anymore.”",
      "Aurelia adjusted the return settings.",
      "“One year in the past is equal to one hour in the present,” she said. “Your forty-three-minute visit will be safe, and when the timer reaches zero, the machine will bring you back automatically.”",
      "“What if I don’t want to come back?” Tomas asked.",
      "Aurelia looked at him seriously for two seconds before answering.",
      "“Then the machine will bring you back while you complain, cry, argue, and promise that you only need five more minutes.”",
      "Tomas gave her a nervous smile.",
      "Aurelia smiled back, but her fingers remained still above the activation button.",
      "She had learned that customers often believed they knew what they wanted. Most of them did not understand that visiting the past was not like opening an old photograph. The past was alive. It had sounds, smells, weather, mistakes, and people who had no idea that someone from the future was watching them.",
      "Some customers wanted to see dead relatives.",
      "Some wanted to apologize to people they had hurt.",
      "Some wanted to prevent a bad decision.",
      "Others wanted to see whether their lives would have become better if they had chosen a different school, married a different person, accepted a different job, or stayed in a place they had once abandoned.",
      "The machine could give them answers.",
      "It could not always give them peace.",
      "Aurelia checked the chamber again.",
      "“Do you have any objects with you?” she asked.",
      "“Only my wallet and this notebook,” Tomas replied.",
      "“Show me the notebook.”",
      "Tomas carefully removed it from his bag and held it up. The brown cover was worn at the edges, and several pages were held together with clear tape. Inside were faded photographs, old handwriting, and short messages written in different colors of ink.",
      "At the center was a photograph of a young man wearing a green polo shirt.",
      "Aurelia leaned closer.",
      "“That’s your father?” she asked.",
      "Tomas nodded.",
      "“He died before I could tell him I forgave him,” he answered.",
      "Aurelia looked at the photograph for a moment.",
      "“Maybe he already knew,” she said.",
      "Tomas looked at her with a confused expression.",
      "“Do you believe that?”",
      "Aurelia shrugged.",
      "“I believe parents know more than we think,” she replied. “They just pretend not to because they enjoy watching us struggle.”",
      "Tomas smiled weakly.",
      "Aurelia pressed the activation button.",
      "The lights in the room dimmed, and the silver rings began to turn around the glass chamber. A low vibration passed through the floor and traveled up Aurelia’s legs.",
      "Tomas gripped the handles inside the chamber.",
      "This time, he did not complain.",
      "Aurelia watched the numbers change across the screen.",
      "1998",
      "JUNE 14",
      "11:20 A.M.",
      "DESTINATION CONFIRMED",
      "The air inside the chamber became bright and soft. Tomas’s body began to blur around the edges, as if he were being reflected in moving water. His bag remained secured against his side, and the notebook was safely closed inside it.",
      "Aurelia raised her voice over the growing hum of the machine.",
      "“Remember the rules!” she called.",
      "Tomas nodded, although his eyes were already shining with tears.",
      "“Speak honestly, but do not control his choices!” Aurelia continued. “Do not change the accident, do not leave the notebook behind, and return before the timer ends!”",
      "“I understand!” Tomas shouted.",
      "The white light swallowed him.",
      "The chamber became empty.",
      "Aurelia leaned back in her chair and released a long breath, allowing her shoulders to relax only after the machine confirmed that Tomas had arrived safely.",
      "For the next forty-three minutes, the underground room was quiet.",
      "Aurelia opened her laptop and returned to her game-development project. A group of cartoon robots appeared on the screen, standing beside a bright blue river in a colorful digital forest.",
      "One robot was supposed to walk across a bridge, collect a golden coin, and continue toward the next level.",
      "Instead, it kept spinning in circles.",
      "Aurelia stared at the screen.",
      "“You and I have the same problem,” she told the robot. “We know where we’re supposed to go, but somebody forgot to give us proper directions.”",
      "The robot spun again.",
      "Aurelia laughed so loudly that the sound echoed against the concrete walls.",
      "At exactly 12:03 p.m., the machine activated.",
      "The silver rings turned in reverse, drawing the blue light back toward the center of the chamber. A bright shape formed behind the glass, and Tomas returned with tears running down his cheeks.",
      "His knees gave out as soon as the chamber opened.",
      "Aurelia immediately stood and hurried toward him.",
      "“Are you hurt?” she asked while reaching for his arm.",
      "Tomas shook his head and held the notebook tightly against his chest.",
      "“I saw him,” he whispered.",
      "Aurelia helped him stand.",
      "“What happened?” she asked.",
      "“He remembered me,” Tomas answered.",
      "“That’s good,” Aurelia said gently.",
      "“I was only six,” Tomas continued. “He remembered the toy car I broke in his room, and he told me I was a terrible mechanic.”",
      "Tomas laughed through his tears.",
      "Aurelia smiled.",
      "“Was he right?” she asked.",
      "“I think so.”",
      "They stood together in the middle of the room, surrounded by the quiet machine and the soft blue lights along the floor. Tomas slowly opened the notebook, expecting to see the same old pages and photographs.",
      "Then he stopped.",
      "A new line of writing had appeared beneath the old messages.",
      "Aurelia leaned closer.",
      "The handwriting was different from the rest.",
      "You were always my best invention.",
      "Tomas touched the words with shaking fingers.",
      "Aurelia felt warmth rise in her chest. The notebook had traveled from the present into the past and returned safely with Tomas. It had not been left behind, copied, or used to change history. The only thing that had changed was the message written by a father who had finally been given the chance to say what he could not say before.",
      "Sometimes, Aurelia thought, that was enough.",
      "Tomas paid the remaining balance before leaving. At the laboratory door, he turned toward her with one hand resting on the handle.",
      "“Do you ever travel for yourself?” Tomas asked.",
      "Aurelia leaned against the control table.",
      "“Sometimes,” she answered.",
      "“To see your parents?” Tomas asked.",
      "Aurelia’s smile faded.",
      "For a moment, the room became too quiet. The machine stood behind her, tall and silent, while the blue lights reflected against the glass chamber.",
      "Aurelia looked toward it.",
      "“No,” she said softly. “Not anymore.”",
      "Tomas seemed to understand that she did not want to explain.",
      "He left without asking another question.",
      "Aurelia locked the laboratory door and checked the security cameras. The hallway outside was empty, and above the laboratory, her grandmother was probably preparing lunch and reminding her that she had skipped breakfast again.",
      "Aurelia removed her glasses and rubbed her tired eyes before returning to the control panel.",
      "Then the machine made a sound.",
      "One of the screens turned on by itself.",
      "A line of text appeared.",
      "NEXT REQUEST RECEIVED.",
      "Aurelia frowned and stepped closer.",
      "She had not opened the customer system.",
      "The screen remained blank beneath the message.",
      "No name appeared.",
      "No date appeared.",
      "No location appeared.",
      "Only the words remained, glowing against the dark screen.",
      "Aurelia reached toward the keyboard, but the system shut down before her fingers touched it.",
      "From somewhere upstairs, her grandmother called her name.",
      "“Aurelia! Your food is getting cold!”",
      "Aurelia looked at the silent machine.",
      "For the first time that day, she did not make a joke.",
      "She walked toward the stairs, but kept looking behind her as she climbed.",
      "The machine remained still.",
      "Waiting."
    ]
  },
  {
    "key": "Chapter 1",
    "title": "December 25, 2017",
    "paragraphs": [
      "Aurelia Veyne woke up because someone was knocking on her bedroom door with the patience of a person who had already knocked several times and was now considering using a more serious method.",
      "She opened one eye and stared at the ceiling.",
      "The room was still dark, except for the pale morning light slipping through the gap between her curtains. Her computer monitor glowed on the desk, displaying several lines of colorful code and a small cartoon robot trapped inside a wall. The robot’s right leg was raised in the air, its left arm pointed toward the ceiling, and its round head had turned backward as if it had completely forgotten which direction was forward.",
      "A half-empty cup of coffee sat beside the keyboard. Three screwdrivers were scattered across her pillow, a roll of electrical tape hung from the edge of her bed, and a small circuit board rested beside her sleeping hand.",
      "Another knock sounded.",
      "“Aurelia,” her grandmother called from the other side of the door. “If you are awake, answer me. If you are not awake, wake up.”",
      "Aurelia pulled the blanket over her head.",
      "“I am emotionally awake,” she answered, her voice muffled by the blanket. “My body is still under maintenance.”",
      "The door opened.",
      "Her grandmother entered while carrying a plate of fried eggs, rice, and sliced tomatoes. She was a small woman in her fifties with long, dark hair tied loosely behind her neck, although several silver strands had begun to appear near her temples. She had fair skin, dark brown eyes, and delicate features that made her look like an older version of Aurelia.",
      "The difference was that Grandma’s eyes held years of knowledge that Aurelia still did not understand.",
      "Grandma placed the plate on the small table beside the bed.",
      "“Your body has been under maintenance for twelve hours,” Grandma said. “It is time to restart the system.”",
      "Aurelia slowly pushed herself into a sitting position, and her straight black hair fell across her face.",
      "“Can I install breakfast later?” Aurelia asked.",
      "“No,” Grandma answered.",
      "“What about a trial version?” Aurelia asked.",
      "“No.”",
      "“Free software?”",
      "“Eat.”",
      "Aurelia looked at the plate and smiled despite herself. She was wearing an oversized shirt and loose shorts, and one of her socks was hanging from the back of a chair. Her room was small but crowded with the things she loved: old keyboards, circuit boards, miniature gears, wires, batteries, notebooks, game controllers, empty electronic boxes, and several unfinished inventions that had never reached the stage of becoming useful.",
      "She pulled the plate closer and picked up her fork.",
      "Grandma glanced at the computer monitor.",
      "“You worked again last night,” Grandma said.",
      "“I was testing the robot’s walking pattern,” Aurelia replied.",
      "“The robot is walking into a wall.”",
      "“He is exploring new possibilities.”",
      "“He has been exploring the same wall since midnight.”",
      "Aurelia took a bite of egg and spoke while chewing.",
      "“Maybe the wall is important to the story.”",
      "“Maybe the programmer needs sleep,” Grandma replied.",
      "Aurelia swallowed and raised her fork.",
      "“I am both the programmer and the story.”",
      "Grandma studied her for a moment, and her expression softened. Aurelia noticed the look but did not ask about it. Her grandmother had always been kind to her, but there were moments when that kindness seemed to carry a quiet sadness. Grandma sometimes looked at Aurelia as if she were remembering something that had not happened yet.",
      "Aurelia had learned not to force her to explain every silence.",
      "She took another bite of egg, burned her tongue, and immediately pulled a face.",
      "“Hot,” Aurelia mumbled.",
      "“That is usually what happens when you eat food immediately after it is cooked,” Grandma replied.",
      "“I thought it was a surprise attack.”",
      "“You are twenty-two years old.”",
      "“Exactly,” Aurelia said. “I am still young enough to be attacked by eggs.”",
      "Grandma shook her head, but a small smile appeared on her face.",
      "Aurelia’s phone began vibrating on the bed.",
      "She reached for it and looked at the screen. There were five missed calls, three messages from her game-development team, and one encrypted notification from the private customer system hidden behind an ordinary calendar application.",
      "Her smile slowly disappeared.",
      "Grandma noticed the change in her face.",
      "“Time-travel work?” Grandma asked.",
      "“Yes,” Aurelia answered.",
      "She did not need to lie. Grandma already knew about the machine, the secret customers, the expensive equipment, the rules, and the dangers of allowing people to cross through time.",
      "Grandma had helped Aurelia understand quantum theory, physics, mathematics, logic, and the relationship between matter and energy. She had corrected Aurelia’s calculations when she was still a child, and she had been present when Aurelia first realized that her theories could become a working machine.",
      "The machine would not exist without her.",
      "Aurelia placed her fork down.",
      "“There is a strange request in the system,” she said.",
      "Grandma walked closer to the bed.",
      "“What kind of strange?” Grandma asked.",
      "“Unknown sender, no payment record, no contact information, and no referral code,” Aurelia explained while turning the phone so Grandma could see the screen. “It appeared on the laboratory screen first, but there was no destination listed. Now it is on my phone.”",
      "Grandma read the message carefully.",
      "NEXT REQUEST RECEIVED.",
      "Beneath it, another line appeared.",
      "DESTINATION CONFIRMED: DECEMBER 25, 2017.",
      "Grandma’s expression changed.",
      "Aurelia noticed immediately.",
      "“Grandma?” Aurelia asked.",
      "Her grandmother did not answer right away. She took the phone from Aurelia and read the message again, as if the words might become different if she looked at them a second time.",
      "“Did the system provide a location?” Grandma asked.",
      "“No.”",
      "“Did it provide a return point?”",
      "“No.”",
      "“Did you receive a customer identity?”",
      "“No.”",
      "Grandma looked back at the screen.",
      "“Then we do not accept it yet,” she said.",
      "“I know.”",
      "“We inspect the machine, check the security records, and confirm whether the request is real or corrupted,” Grandma continued. “Then we shut down the customer system until we understand how it appeared.”",
      "Aurelia made a small face.",
      "“Do we have to shut it down?”",
      "Grandma looked at her seriously.",
      "“Aurelia.”",
      "“I know, I know,” Aurelia said. “Safety first.”",
      "“Not just safety,” Grandma replied gently. “Responsibility first. You have customers who trust you with parts of their lives. If the system can create a request without an identity or a return point, we cannot allow anyone to use it until we understand what happened.”",
      "Aurelia nodded.",
      "She knew Grandma was right, even if she did not like hearing it.",
      "Grandma reached for the phone and studied the screen again.",
      "“Did you activate anything?” Grandma asked.",
      "“No. I only opened the request.”",
      "“Good.”",
      "“I tried calling the sender, but the connection was unavailable.”",
      "“Then it may not have come from a person in our present,” Grandma said.",
      "Aurelia frowned.",
      "“You think it came from the past?”",
      "“I said it may not have come from a person in our present,” Grandma replied.",
      "“That sounds like a very careful way of saying something scary.”",
      "“It is a careful way of saying that we should not guess before we have evidence.”",
      "Aurelia looked down at the message.",
      "The date felt strangely heavy.",
      "December 25, 2017.",
      "She knew exactly what happened during that year. She had been twelve years old. Her parents had been traveling by plane. The aircraft had disappeared, and no bodies had ever been recovered. The authorities had searched for weeks, but the ocean gave back nothing. Her parents became names in a report, faces in old photographs, and memories that grew more painful every year.",
      "Aurelia had been at the airport when the news arrived.",
      "She remembered the waiting area, the cold air-conditioning, the sound of people speaking in frightened voices, and the way Grandma had held her hand so tightly that it hurt.",
      "She remembered asking whether her parents were still alive.",
      "She remembered Grandma not answering.",
      "“Why would anyone want to travel to that date?” Aurelia asked.",
      "“There may be many reasons,” Grandma replied.",
      "“Maybe they want to see someone.”",
      "“Most customers do.”",
      "“Maybe they want to stop something.”",
      "“Then we reject them.”",
      "“Maybe they want to find someone who disappeared.”",
      "Grandma’s eyes lowered to the phone.",
      "“That date is connected to your parents,” Grandma said quietly.",
      "“I know,” Aurelia answered.",
      "“Then you need to be more careful than usual.”",
      "Aurelia gave her a small smile.",
      "“I am always careful.”",
      "Grandma looked toward the three screwdrivers on the pillow, the open circuit board near the bed, and the coffee cup balanced dangerously close to the edge of the table.",
      "“You once connected a power supply backward because you said the wires looked lonely,” Grandma reminded her.",
      "“The wires were lonely.”",
      "“The entire room filled with smoke.”",
      "“It was very dramatic.”",
      "Grandma reached over and gently fixed a loose strand of Aurelia’s hair behind her ear.",
      "“Be careful,” Grandma repeated.",
      "This time, Aurelia did not joke.",
      "“I will,” she promised.",
      "Grandma stood and picked up the empty plate.",
      "“You have work today?” Grandma asked.",
      "“Yes,” Aurelia answered. “We are testing the new level of the game.”",
      "“What game?”",
      "“A cooperative adventure game about a group of students who explore an abandoned research station.”",
      "“Does the robot walk into walls?”",
      "“That is a different game.”",
      "“Then you have too many games.”",
      "“I have exactly the right number of games.”",
      "Grandma moved toward the door.",
      "“Bring your lunch.”",
      "“I will.”",
      "“Drink water.”",
      "“I will.”",
      "“Do not stay at the office until midnight.”",
      "“I will try.”",
      "Grandma stopped and looked over her shoulder.",
      "“Trying is not the same as doing.”",
      "Aurelia smiled.",
      "“Fine. I will do my best.”",
      "Grandma nodded before leaving the room.",
      "Aurelia copied the request information to a secure drive, changed into a clean shirt, tied her hair into a messy ponytail, and placed her laptop inside her bag. Before leaving the room, she looked at the cartoon robot on her computer screen.",
      "It was still standing inside the wall.",
      "“I will fix you later,” Aurelia told it.",
      "The robot continued staring at the ceiling.",
      "Aurelia picked up the fallen screwdriver from the floor and placed it on the desk before hurrying downstairs.",
      "The underground laboratory was beneath the house, hidden behind a tall storage cabinet in the back room. Aurelia pulled the cabinet forward, entered a code into the keypad, and waited for the wall to open.",
      "A narrow staircase descended into darkness.",
      "The motion-sensor lights turned on one by one as Aurelia walked down, revealing concrete walls, metal railings, and wires running along the ceiling. She had built the laboratory slowly over several years, beginning with a storage room and eventually turning it into a private research facility.",
      "The machine stood at the center of the room.",
      "Two enormous silver rings surrounded a clear glass chamber. Each ring was covered in small lights and narrow metal panels. The chamber had enough space for two people to stand inside, but no more. Aurelia had designed the machine that way on purpose.",
      "Only two quantum identities could be stabilized during one jump.",
      "A third person could cause identity overlap, memory corruption, or a temporal collision.",
      "Aurelia reached the control table and opened the main system.",
      "The request was still there.",
      "DESTINATION CONFIRMED: DECEMBER 25, 2017.",
      "She entered the system log.",
      "The request had appeared at 12:03 p.m., exactly when Tomas returned from his trip to 1998.",
      "She checked the security records.",
      "Nothing.",
      "No one had opened the laboratory door.",
      "No outside device had connected to the server.",
      "No customer account had accessed the application.",
      "Aurelia leaned closer to the screen.",
      "“There has to be a reason,” she whispered.",
      "She opened the machine’s travel history.",
      "The previous trip was listed normally:",
      "CUSTOMER: TOMAS REYES",
      "DESTINATION: JUNE 14, 1998",
      "DURATION: FORTY-THREE MINUTES",
      "OBJECTS RETURNED: ONE NOTEBOOK",
      "TIMELINE STATUS: STABLE",
      "Aurelia scrolled down.",
      "The next entry was not normal.",
      "CUSTOMER: UNKNOWN",
      "DESTINATION: DECEMBER 25, 2017",
      "DURATION: UNAVAILABLE",
      "RETURN POINT: UNAVAILABLE",
      "TIMELINE STATUS: PENDING",
      "Aurelia’s skin prickled.",
      "She had never seen the word pending in the machine’s travel records. The machine was either stable or unstable. It either had a confirmed return point or it did not.",
      "Pending meant that something had been started but not completed.",
      "Aurelia looked at the glass chamber.",
      "The door was closed, and the inside was empty. She walked around it slowly, checking the metal rings and the floor beneath the platform.",
      "There were no footprints, broken wires, or signs that anyone had entered.",
      "Then she noticed a faint mark on the glass.",
      "It was shaped like a handprint.",
      "Aurelia brought her fingers close to it without touching the surface.",
      "The mark was on the inside.",
      "She stepped back.",
      "The laboratory door opened behind her.",
      "Aurelia spun around.",
      "Lucian Vale entered the room carrying a paper bag from a nearby café. He was in his early fifties, with neatly combed gray hair, thin glasses, and a gentle smile that made him look more like a university professor than someone who understood machines capable of crossing time.",
      "He had been Aurelia’s professor, mentor, and one of the few adults who had treated her inventions seriously when she was younger.",
      "He had also become the closest thing she had to a father after her parents died.",
      "“You left the upstairs door open,” Lucian said, holding up the paper bag. “Your grandmother said I would find you here.”",
      "Aurelia glanced toward the handprint.",
      "Lucian followed her gaze.",
      "“What happened?” Lucian asked.",
      "“I do not know yet,” Aurelia replied.",
      "Lucian placed the paper bag on the control table and removed two cups of coffee.",
      "“I brought breakfast.”",
      "“I already ate.”",
      "“You can drink coffee.”",
      "“Grandma says I drink too much.”",
      "“Your grandmother is usually right.”",
      "“That is a dangerous thing to say around her,” Aurelia said. “She will frame it and hang it above the kitchen sink.”",
      "Lucian chuckled while removing his glasses to clean them with a small cloth.",
      "Aurelia did not smile this time.",
      "“Professor, did you access the customer system?” Aurelia asked.",
      "Lucian’s eyebrows lifted.",
      "“Good morning to you too,” he replied.",
      "“I am serious.”",
      "“So am I,” Lucian said. “You look like you have not slept.”",
      "“Did you access it?”",
      "Lucian placed his glasses back on his face.",
      "“No, I did not,” he answered.",
      "Aurelia continued watching him.",
      "“Why would I access your private system?” Lucian asked.",
      "“Because a request appeared without a customer name.”",
      "“That sounds like a security problem.”",
      "“It is.”",
      "“What date?”",
      "Lucian’s expression remained neutral.",
      "“Did you ask me because you already know?” Lucian asked.",
      "Aurelia did not answer.",
      "Lucian turned toward the machine.",
      "“What is the destination?” he asked.",
      "“December 25, 2017.”",
      "For a brief moment, his face changed. His mouth stopped moving, and his eyes shifted toward the floor before he looked back at her.",
      "“That is an unusual date,” Lucian said.",
      "“That is what I thought.”",
      "“Do you know anyone who wants to travel there?”",
      "“No.”",
      "“Then it may be a corrupted entry.”",
      "“The system does not create entries by itself.”",
      "“Systems do strange things when their creators forget to sleep.”",
      "Aurelia crossed her arms.",
      "“You sound like Grandma.”",
      "“Your grandmother is usually right,” Lucian replied.",
      "“That is the second time someone has said that today. I am starting to feel surrounded.”",
      "Lucian stepped closer to the control screen and studied the information. His eyes passed over the unknown customer record, the missing return point, and the word pending.",
      "“What do you think?” Aurelia asked.",
      "Lucian placed both hands on the table.",
      "“I think you should not activate the machine until you understand how this entry was created,” he said.",
      "“That is what Grandma said.”",
      "“Then listen to both of us.”",
      "Aurelia looked at the handprint again.",
      "“Do you think someone came inside?” she asked.",
      "“Perhaps,” Lucian replied.",
      "“There is no security footage.”",
      "“Then perhaps the system recorded the request before the person arrived.”",
      "Aurelia turned toward him.",
      "“That makes no sense.”",
      "“Most important discoveries begin as things that make no sense.”",
      "She studied his face.",
      "“Did you ever see this kind of error in your research?”",
      "“Not this exact error,” Lucian answered.",
      "“But something similar?”",
      "He took a sip of coffee before answering.",
      "“Time is not a straight line, Aurelia. You already know that. Sometimes a system can receive information before the event that creates it.”",
      "Aurelia felt a chill move through her arms.",
      "“That sounds like a closed loop.”",
      "“It could be.”",
      "“Closed loops are dangerous.”",
      "“They are dangerous when people try to control them.”",
      "Aurelia looked at the screen again.",
      "The unknown request remained open.",
      "“What should I do?” she asked.",
      "Lucian’s voice became gentler.",
      "“Do not touch it yet. Go to work, finish your game, eat your lunch, and let your mind rest. When you return, we can inspect the system together.”",
      "Aurelia wanted to argue, but she knew he was right.",
      "She closed the log and saved a copy of the information to an external drive. Before leaving, she looked at the glass chamber one more time.",
      "The handprint was still there.",
      "Lucian followed her gaze.",
      "“Did you clean the glass recently?” he asked.",
      "“No,” Aurelia replied.",
      "“You should.”",
      "“Why?”",
      "“It is difficult to investigate a machine when you cannot see through it.”",
      "Aurelia gave him a suspicious look.",
      "“That was not a real answer.”",
      "“It was the answer I had,” Lucian replied with a smile.",
      "They left the laboratory together.",
      "Aurelia locked the door behind her and returned the cabinet to its place. She carried her lunchbox in one hand and her laptop bag in the other while Lucian walked beside her toward the front door.",
      "Outside, the morning sun had risen over Laguna. The road in front of the house was already busy with motorcycles, tricycles, and students walking toward school. The air was warm, and the smell of damp soil rose from the garden.",
      "Lucian stepped toward his car.",
      "Aurelia checked her phone.",
      "The unknown request was still there.",
      "She opened it again.",
      "A new option had appeared beneath the date.",
      "ACCEPT INVESTIGATION?",
      "Aurelia stared at the screen.",
      "She had not created that option.",
      "Lucian noticed her silence.",
      "“What is it?” he asked.",
      "“The system is asking me to accept the request.”",
      "“Do not press anything,” Lucian instructed.",
      "Aurelia looked at him.",
      "“Grandma said not to activate it.”",
      "“And I am saying the same thing.”",
      "“What if the request is from someone who needs help?”",
      "“Then we find out who sent it before we send you anywhere.”",
      "Aurelia looked toward the house.",
      "Grandma was standing behind the window, watching them from inside. Even from a distance, Aurelia could see that she was worried.",
      "Aurelia raised one hand to let her know everything was fine.",
      "Grandma did not smile.",
      "Lucian unlocked his car.",
      "“You are coming to work with me,” he said. “We will talk about the request later.”",
      "Aurelia hesitated.",
      "Her game-development team was waiting for her. She had a meeting in less than an hour, and her project manager would probably send another message asking why the level designer was trapped inside a wall.",
      "But the date on the screen kept pulling at her attention.",
      "December 25, 2017.",
      "It was the year her parents disappeared.",
      "It was the year she had first learned that some people could leave without ever coming back.",
      "Aurelia placed her phone in her pocket.",
      "“I will go to work,” she said. “But I am checking the request again tonight.”",
      "Lucian nodded.",
      "“That is reasonable.”",
      "“After Grandma checks it too.”",
      "“That is wise.”",
      "“And I am bringing Adrian’s old programming notes.”",
      "Lucian glanced at her.",
      "“Who is Adrian?”",
      "Aurelia paused.",
      "She did not know why she had said the name.",
      "It had been written in one of her notebooks for years, connected to an old programming theory she had once found in an abandoned online archive. She had never met him. She knew only that he had worked as an IT analyst in 2017 and had written several small programs that had inspired some of her own systems.",
      "She had always wanted to know more about him.",
      "“Adrian Aurex,” Aurelia explained. “He was a programmer from 2017 whose work helped me understand some of the older system structures.”",
      "Lucian watched her carefully.",
      "“He is connected to the request?”",
      "“I do not know,” Aurelia answered. “That is why I want to investigate.”",
      "Lucian opened the passenger door.",
      "“Then investigate carefully.”",
      "Aurelia entered the car and placed her lunchbox on her lap.",
      "Lucian started the engine.",
      "For a few minutes, neither of them spoke. The road carried them away from the house and toward the highway, where buses, jeepneys, and motorcycles moved through the morning traffic. Aurelia watched the houses pass by through the window, but her thoughts remained inside the laboratory.",
      "She had built the machine to help people visit moments they had lost.",
      "She had created rules so those visits would remain safe.",
      "She had accepted money from customers because the machine required expensive materials, private facilities, and years of work to maintain.",
      "But she had never imagined that the machine could receive a request from someone who did not exist in the system.",
      "She had never imagined that the request could come from a date connected to the worst day of her life.",
      "Lucian glanced at her.",
      "“You are thinking too loudly,” Lucian said.",
      "Aurelia turned toward him.",
      "“I do not make sounds when I think.”",
      "“You do when you are worried,” Lucian replied. “You tap your thumb against your fingers.”",
      "Aurelia looked down.",
      "Her thumb was tapping against each finger.",
      "She quickly stopped.",
      "“You have been watching me,” Aurelia said.",
      "“I was your professor for four years,” Lucian replied.",
      "“You were watching me before that.”",
      "Lucian smiled at the road.",
      "“You were not very difficult to notice. You were the girl who built a working alarm system inside a pencil case.”",
      "“It worked.”",
      "“It shocked me when I tried to open it.”",
      "“You touched the warning label.”",
      "“It said ‘do not touch.’”",
      "“That was the warning.”",
      "Lucian laughed, and Aurelia laughed with him.",
      "The moment felt normal and comfortable. That was what made it difficult for Aurelia to remain suspicious.",
      "Lucian had helped her when she had no one else. He had corrected her calculations, lent her equipment, introduced her to people who could provide materials, and encouraged her when the university rejected her application for the course she truly wanted.",
      "He had never treated her like she was incapable because she was young.",
      "He had never laughed at her dream of building a machine that could cross time.",
      "To Aurelia, Lucian was not only a professor.",
      "He was family.",
      "Aurelia looked down at her phone one more time.",
      "The request remained open.",
      "No sender.",
      "No return point.",
      "No explanation.",
      "Only a destination date and one name that had come into her mind before she understood why.",
      "Adrian Aurex.",
      "Aurelia did not know that by the end of the day, she would meet him.",
      "She did not know that the airport would bring them together.",
      "She did not know that Adrian would be twenty-two years old, living in Makati, working as an IT analyst, and saying goodbye to his parents on the same day she was searching for hers.",
      "She only knew that the machine had given her a question.",
      "And Aurelia had never been good at leaving questions unanswered."
    ]
  },
  {
    "key": "Chapter 2",
    "title": "The Boy at the Airport",
    "paragraphs": [
      "By the time Aurelia arrived at the game studio, the morning traffic had already turned the streets into a slow-moving line of cars, jeepneys, motorcycles, and impatient drivers. She sat in the passenger seat of Lucian’s car while holding her lunchbox against her stomach, watching the city pass through the window in pieces of glass, concrete, signs, wires, and people rushing toward places that probably mattered to them.",
      "Her phone remained in her hand.",
      "The time-travel request was still open.",
      "DESTINATION CONFIRMED: DECEMBER 25, 2017.",
      "CUSTOMER: UNKNOWN.",
      "RETURN POINT: UNAVAILABLE.",
      "Beneath the information was the name that had appeared in her thoughts before she understood why.",
      "ADRIAN AUREX.",
      "Aurelia did not know him personally. She had never met him, spoken with him, or even seen a recent photograph of him. She had only encountered his name years ago while studying old programming forums and archived system designs.",
      "Adrian Aurex had written simple but clever programs that focused on system organization, data movement, and error detection. His work was not famous, and his name did not appear in textbooks, but Aurelia had found his methods useful when she was developing the machine’s early control software.",
      "He had been twenty-two in 2017.",
      "He had worked as an IT analyst in Makati.",
      "That was all Aurelia knew.",
      "She did not understand why the request had made her think of him.",
      "Lucian glanced at her while keeping his eyes on the road.",
      "“You have been staring at that phone since we left the house,” he said.",
      "Aurelia locked the screen and placed the phone against her thigh.",
      "“I am studying it.”",
      "“You are holding it upside down.”",
      "Aurelia looked down.",
      "The screen was, in fact, upside down.",
      "She turned it around and cleared her throat.",
      "“I was studying it from another perspective.”",
      "Lucian smiled slightly.",
      "“That is not how perspective works.”",
      "“It is how creativity works.”",
      "“Creativity is not an excuse for poor phone handling.”",
      "Aurelia looked at him with a tired expression.",
      "“Why are you always against my artistic process?”",
      "“Because your artistic process almost caused a traffic accident last month.”",
      "“That traffic accident was not my fault.”",
      "“You were trying to repair a drone while crossing the road.”",
      "“The drone was suffering.”",
      "“The driver was also suffering.”",
      "Aurelia laughed quietly and leaned her head against the window. Lucian joined her laughter for a moment, and the car became comfortable again.",
      "That comfort made the request feel even stranger.",
      "Lucian was the person who had encouraged her to investigate the machine. He had warned her not to activate an unknown destination. He had told her to wait until they understood the system.",
      "He was not hiding anything from her.",
      "At least, Aurelia had no reason to believe that he was.",
      "Still, the words RETURN POINT: UNAVAILABLE remained inside her mind.",
      "She looked at the screen again.",
      "“Professor,” Aurelia said, her voice more serious this time, “what happens if a request arrives without a return point?”",
      "Lucian’s hands tightened slightly around the steering wheel.",
      "“It depends on how the request was created,” he answered.",
      "“What if the customer is already connected to the machine?”",
      "“Then the system may be waiting for the traveler to complete the jump.”",
      "“What if the traveler is from the future?”",
      "Lucian did not answer immediately.",
      "Aurelia watched his reflection in the window.",
      "“That is possible, right?” she asked.",
      "“Anything is theoretically possible,” Lucian replied carefully. “But not everything is safe.”",
      "“That did not answer my question.”",
      "“It answered enough of it.”",
      "Aurelia crossed her arms.",
      "“You always do that when you do not want to explain something.”",
      "“I do that when I want you to think before acting.”",
      "“I think all the time.”",
      "“You joke all the time. That is different.”",
      "Aurelia smiled despite herself.",
      "Lucian turned the car toward the road leading to the game studio.",
      "“The request may be a temporary communication error,” he said. “It may have been created by a failed synchronization between the customer server and the machine.”",
      "“But the destination is a specific date.”",
      "“That does not prove that a person chose it.”",
      "“And the name Adrian Aurex?”",
      "Lucian looked at her briefly.",
      "“What name?”",
      "Aurelia realized that she had spoken aloud.",
      "She touched the edge of her phone.",
      "“Nothing.”",
      "Lucian gave her a questioning look but did not press her.",
      "That was one of the reasons Aurelia trusted him. He knew when to ask questions, but he also knew when to leave space for someone to answer on their own.",
      "The game studio occupied two floors of a renovated office building in Quezon City. The outside walls were painted white, but several large windows were covered with posters from the company’s previous games. A giant cartoon monster holding a sword stood beside the entrance, smiling with too many teeth.",
      "Aurelia always thought it looked friendly.",
      "Her teammates thought it looked frightening.",
      "She entered the building with Lucian and waved at the security guard, who recognized her immediately.",
      "“Good morning, Miss Aurelia,” the guard greeted her.",
      "“Good morning, Kuya Ben,” Aurelia replied cheerfully. “Did the monster behave today?”",
      "Kuya Ben glanced at the poster.",
      "“He has been staring at me since six in the morning,” he said. “I think he knows I forgot to finish the game.”",
      "Aurelia placed one hand against her chest.",
      "“You should apologize before he grows arms.”",
      "“He already has arms.”",
      "“That is worse.”",
      "Kuya Ben laughed as Aurelia walked toward the elevator.",
      "Lucian pressed the button.",
      "“You are cheerful for someone who received an impossible time-travel request,” he observed.",
      "“I can be worried and funny at the same time.”",
      "“That is true.”",
      "“The brain has many tabs open.”",
      "“And how many of yours are currently frozen?”",
      "Aurelia looked at him.",
      "“Most of them.”",
      "The elevator doors opened, and they stepped inside. Two employees from another department entered after them, carrying laptops and paper cups. Aurelia stood in the corner while Lucian checked his phone.",
      "Her reflection appeared on the metal elevator wall.",
      "She looked small beside the other people, barely five feet tall, with straight black hair tied into a loose ponytail and several strands falling across her face. She pushed them behind her ear and noticed that she had forgotten to wear her glasses again.",
      "The elevator stopped on the fifth floor.",
      "Aurelia stepped out and waved at Lucian.",
      "“I will see you later.”",
      "“Message me before you do anything with the machine,” Lucian reminded her.",
      "“I will.”",
      "“Promise.”",
      "Aurelia placed two fingers over her heart.",
      "“I promise.”",
      "Lucian studied her face before the elevator doors closed.",
      "Aurelia turned toward the office.",
      "Her team was already gathered around the main screen.",
      "Darren, the project manager, stood with his arms crossed while a large red error message covered the game’s opening level. He was twenty-eight years old, always wore a headset around his neck, and had the exhausted expression of a man who had spent too much time explaining the same problem to people who had not listened.",
      "Aurelia placed her laptop bag beside her desk.",
      "“Good morning,” she said.",
      "Darren looked at her.",
      "“Good morning,” he replied. “The robot has become a criminal.”",
      "Aurelia blinked.",
      "“What did he do?”",
      "“He stole the player’s inventory, walked through a wall, and disappeared into the floor.”",
      "Aurelia opened her laptop.",
      "“He is not a criminal. He is confused.”",
      "“He has caused three testers to lose their progress.”",
      "“That sounds personal.”",
      "Darren pointed toward the screen.",
      "“Fix him before the afternoon test.”",
      "Aurelia sat down and began reviewing the code.",
      "Her work as a game developer was supposed to be ordinary. She wrote systems, tested movement, repaired bugs, built maps, and worked with artists and designers to create worlds where people could escape for a few hours.",
      "She enjoyed it more than she expected.",
      "There was something comforting about game development. When a character fell through the floor, there was usually a reason. When a door refused to open, someone had forgotten a line of code. When a player became trapped in a wall, the problem could be found, studied, and repaired.",
      "Time was not so cooperative.",
      "Aurelia worked for almost an hour before she found the error. A movement value had been copied into the wrong section of the program, causing the robot to interpret the wall as a walking path.",
      "She corrected the code and ran the test again.",
      "The robot walked across the bridge.",
      "It collected the golden coin.",
      "It waved at the player.",
      "Aurelia leaned back in her chair.",
      "“Congratulations,” she told the screen. “You are no longer a public danger.”",
      "Darren looked over her shoulder.",
      "“The robot is working?”",
      "“He has returned to a life of honesty.”",
      "“Good,” Darren said. “Now repair the door that keeps opening into the ceiling.”",
      "Aurelia stared at him.",
      "“Why does every object in this game want to escape?”",
      "“Because you designed it.”",
      "“I designed the world. The objects made their own decisions.”",
      "Darren gave her a tired look and returned to his desk.",
      "Aurelia smiled and opened the private system on her laptop.",
      "The request was still waiting.",
      "She studied the date again.",
      "December 25, 2017.",
      "Aurelia opened a separate file containing historical information. She had built the file for customers who wanted to visit personal moments but did not know the exact location of the event.",
      "The date brought up several records.",
      "A plane disappeared during a Christmas flight.",
      "The passengers included Elias and Mira Veyne.",
      "Aurelia’s parents.",
      "Her fingers became cold against the keyboard.",
      "She closed the file quickly.",
      "She already knew.",
      "She did not need to read the report again.",
      "Instead, she searched the name Adrian Aurex.",
      "The system displayed an old employee record.",
      "NAME: ADRIAN AUREX",
      "AGE (2017): 22",
      "OCCUPATION: IT ANALYST",
      "LOCATION: MAKATI, MANILA",
      "There was no current photograph.",
      "The rest of his information was incomplete.",
      "His employment record ended in December 2017.",
      "Aurelia frowned.",
      "She searched another database.",
      "Nothing.",
      "She searched old programming forums.",
      "Several archived posts appeared, but the account had been inactive for years.",
      "Aurelia opened the oldest post.",
      "The title was:",
      "How to prevent data from being lost during system migration",
      "The post explained a method for protecting information when moving it from one server to another. Adrian had written the explanation in simple language, using a small example involving saved game files.",
      "Aurelia read the paragraph twice.",
      "Then she smiled.",
      "“Saved game files,” she murmured. “At least he understands what matters.”",
      "Her coworker Mina looked over from the next desk.",
      "“Are you talking to a person?” Mina asked.",
      "Aurelia closed the page halfway.",
      "“No.”",
      "“Are you talking to the computer?”",
      "“Yes.”",
      "“Is the computer answering?”",
      "“Not yet.”",
      "Mina stared at her.",
      "Aurelia smiled innocently.",
      "Mina returned to her work.",
      "Aurelia continued reading Adrian’s old posts. He wrote about programming, system errors, and data recovery. His writing was direct and patient, and he often explained difficult ideas as if he were speaking to someone who had never written a line of code.",
      "Aurelia liked him before meeting him.",
      "She told herself it was only because of his work.",
      "At lunchtime, she took her packed meal to the small balcony outside the office. The view showed the tops of buildings, tangled wires, and a road filled with vehicles. She opened the lunchbox Grandma had prepared and found rice, chicken, vegetables, and a small piece of sweet bread hidden beneath the spoon.",
      "Aurelia smiled.",
      "Grandma always said she did not make too much food, but she always added something extra.",
      "Aurelia took a photograph of the bread and sent it to her.",
      "You are emotionally manipulating me again.",
      "Grandma replied almost immediately.",
      "Eat your lunch.",
      "Aurelia sent another message.",
      "The machine received an unknown request.",
      "The reply took longer.",
      "I know. We will discuss it tonight.",
      "Aurelia looked at the words.",
      "Grandma had not asked whether she intended to accept it.",
      "Maybe she already knew.",
      "Aurelia placed her phone beside the lunchbox and ate slowly.",
      "By two in the afternoon, she had finished the robot system, repaired the ceiling door, attended two meetings, and ignored seven messages from Darren asking whether she had tested the new level.",
      "She tested it.",
      "The game worked.",
      "At five, the other employees began leaving. Aurelia stayed at her desk, looking at the request.",
      "The private system displayed a new button.",
      "ACCEPT INVESTIGATION",
      "She had not added the button.",
      "She checked the application code.",
      "The button did not exist in the source files.",
      "Aurelia opened the server logs.",
      "A new line appeared.",
      "AUTHORIZATION: ACCEPTED",
      "No name followed.",
      "No device was listed.",
      "No location appeared.",
      "Aurelia copied the line to her external drive and closed the system.",
      "She called Grandma.",
      "The call connected after two rings.",
      "“Are you coming home?” Grandma asked.",
      "“Yes,” Aurelia answered.",
      "“Are you bringing dinner?”",
      "“I have food at home.”",
      "“That was not my question.”",
      "Aurelia smiled.",
      "“Do you want anything?”",
      "“Nothing expensive.”",
      "“Define expensive.”",
      "“Anything that requires you to sell another year of your life.”",
      "Aurelia’s smile faded slightly.",
      "Grandma often made jokes about the machine, but she never forgot what it cost Aurelia emotionally.",
      "“I will buy noodles,” Aurelia said.",
      "“Good. Come home safely.”",
      "“I will.”",
      "Aurelia ended the call and gathered her things.",
      "She reached the elevator lobby just as a message appeared on her phone.",
      "ACCEPT INVESTIGATION",
      "The button was still waiting.",
      "Aurelia looked around the empty office. Everyone else had already left, and the hallway lights had turned off automatically.",
      "She thought about Grandma’s warning.",
      "She thought about Lucian’s advice.",
      "She thought about the date connected to her parents.",
      "Then she pressed the button.",
      "The screen turned white.",
      "Aurelia’s heart began beating faster.",
      "A new message appeared.",
      "ONE TRAVELER.",
      "ONE FIXED DESTINATION.",
      "RETURN POINT WILL BE CREATED UPON ARRIVAL.",
      "Aurelia stared at the screen.",
      "The machine had never displayed that message before.",
      "She should have shut down the system.",
      "She should have called Grandma.",
      "She should have returned to the laboratory with another person and completed a full inspection.",
      "Instead, she opened the emergency travel application and entered the destination coordinates.",
      "She knew the airport.",
      "She knew the date.",
      "She knew the risk.",
      "Aurelia did not know why she felt that she had to go.",
      "Perhaps it was because the request was connected to the day her parents disappeared.",
      "Perhaps it was because the name Adrian Aurex had appeared in her thoughts.",
      "Perhaps it was because the machine had asked her a question, and Aurelia had never been good at leaving questions unanswered.",
      "She returned home before dinner and told Grandma everything.",
      "Grandma listened from the kitchen table, her hands folded around a cup of tea.",
      "“You accepted the investigation,” Grandma said.",
      "“Yes,” Aurelia replied.",
      "“You went into the system after I told you not to.”",
      "“I did not travel yet.”",
      "“That was not what I asked.”",
      "Aurelia lowered her gaze.",
      "“No,” she admitted.",
      "Grandma remained quiet.",
      "Aurelia expected anger, but Grandma only looked tired.",
      "“I know why you want to go,” Grandma said.",
      "Aurelia’s voice became softer.",
      "“It is connected to Mom and Dad.”",
      "“Yes.”",
      "“And maybe Adrian Aurex.”",
      "Grandma’s eyes changed when she heard the name.",
      "Only for a second.",
      "Aurelia noticed.",
      "“Do you know him?” Aurelia asked.",
      "Grandma looked down at her tea.",
      "“I know the name.”",
      "“How?”",
      "“It appeared in your research.”",
      "“That is not what I asked.”",
      "Grandma raised her eyes.",
      "“You have not met him before.”",
      "“I know that.”",
      "“Then do not create a connection before you have evidence.”",
      "Aurelia leaned back in her chair.",
      "“I am not saying he caused anything.”",
      "“Good.”",
      "“I only want to meet him.”",
      "“Why?”",
      "Aurelia thought about his old programming posts, his patient explanations, and the strange way his name had entered her thoughts.",
      "“I do not know,” she admitted.",
      "Grandma reached across the table and placed her hand over Aurelia’s.",
      "“Then be careful with what you do not know,” she said gently. “Unanswered questions can make people brave, but they can also make people careless.”",
      "Aurelia looked at their hands.",
      "“I will come back quickly.”",
      "“You will return to the same moment you leave.”",
      "“Yes.”",
      "“You will not interfere with your younger self.”",
      "“I will not.”",
      "“You will not change the plane accident.”",
      "Aurelia’s throat tightened.",
      "“I know.”",
      "Grandma squeezed her hand.",
      "“And if something feels wrong, you return immediately.”",
      "“I promise.”",
      "Grandma nodded, but she did not let go of Aurelia’s hand.",
      "Aurelia traveled after midnight.",
      "She changed into practical clothes, tied her hair securely, placed her glasses in her jacket pocket, and carried only a small notebook, a phone, and the emergency return device.",
      "Before entering the machine, she checked the laboratory twice.",
      "The chamber was empty.",
      "The silver rings were stable.",
      "The destination was fixed.",
      "The return point would be created at the moment of arrival.",
      "Aurelia stood inside the chamber and held the handle.",
      "Grandma remained outside the glass.",
      "“Are you ready?” Grandma asked.",
      "Aurelia tried to smile.",
      "“I was born ready.”",
      "“You were born crying.”",
      "“That was my first dramatic performance.”",
      "Grandma smiled faintly.",
      "“Come back safely.”",
      "“I will.”",
      "Aurelia pressed the activation button.",
      "The rings began to turn.",
      "Blue light filled the chamber, and the laboratory slowly disappeared around her. The floor vanished beneath her feet. Her body became weightless, and the air pressed against her skin.",
      "She saw flashes of places and moments she could not understand: a Christmas tree beside a window, an airplane lifting into a gray sky, a boy sitting in front of a computer, and a girl with black hair standing alone in an airport.",
      "Then the light became complete.",
      "Aurelia landed hard against a cold tiled floor.",
      "Sound returned first.",
      "Announcements echoed through a large building. Suitcase wheels rolled across polished floors. Children cried. People spoke on their phones. The smell of coffee and airplane fuel filled the air.",
      "Aurelia opened her eyes.",
      "She was in an airport.",
      "A screen above the departure gates displayed the date:",
      "DECEMBER 25, 2017.",
      "She slowly stood and checked her body.",
      "Everything was intact.",
      "Her phone was still in her pocket.",
      "Her notebook was still inside her jacket.",
      "The emergency return device was secured around her wrist.",
      "The machine had created a return point.",
      "Aurelia looked around the airport.",
      "People moved everywhere, carrying bags and gifts, greeting relatives, and rushing toward departure gates. Christmas decorations hung from the walls, and a large tree stood near the entrance with lights blinking around its branches.",
      "Aurelia felt the familiar pressure in her chest.",
      "She had been here before.",
      "Not as a traveler.",
      "As a child.",
      "Near the glass doors stood a twelve-year-old girl with straight black hair and a pink backpack. The girl kept looking toward the entrance, holding a small phone in both hands.",
      "Aurelia recognized her immediately.",
      "She was herself.",
      "Young Aurelia looked frightened but was trying not to show it.",
      "Aurelia stepped backward.",
      "She could not breathe properly.",
      "The rules returned to her mind.",
      "Do not interfere with your own origin.",
      "Do not reveal yourself.",
      "Do not change the fixed event.",
      "She turned away from the child and walked toward the waiting area.",
      "That was when someone bumped into her shoulder.",
      "Aurelia nearly dropped her phone.",
      "“I’m sorry,” a young man said quickly.",
      "She looked up.",
      "The man was around twenty-two years old, with dark hair, warm eyes, and a lean build. He was not extremely tall, but he was tall enough that Aurelia had to tilt her head slightly to look at him. He wore a simple jacket and carried a small backpack over one shoulder.",
      "He reached for her phone before it hit the floor.",
      "“Are you okay?” he asked while handing it back.",
      "Aurelia accepted the phone.",
      "“Yes,” she replied. “I am okay. My phone is also okay. We both survived.”",
      "The young man smiled.",
      "“That is good.”",
      "Aurelia studied his face.",
      "She already knew him from old programming posts, outdated employee records, and a name that had appeared in a strange time-travel request.",
      "“You are Adrian Aurex,” she said.",
      "His smile slowly disappeared.",
      "“Have we met?” Adrian asked.",
      "Aurelia felt her heart stumble.",
      "She needed to answer carefully.",
      "The airport continued moving around them, unaware that two people from different years had just met beside the Christmas decorations.",
      "Aurelia forced a small smile.",
      "“No,” she answered. “But I think I have heard of you.”",
      "Adrian tilted his head.",
      "“That sounds suspicious.”",
      "“I am told I am suspicious.”",
      "“By who?”",
      "“My grandmother.”",
      "Adrian laughed softly.",
      "It was a quiet, warm laugh that made him look less tired.",
      "Aurelia smiled back.",
      "For the first time since she arrived in 2017, the strange request felt less like a machine problem and more like the beginning of something she did not yet understand.",
      "Behind Adrian, a couple waved toward him.",
      "His parents.",
      "Adrian glanced over his shoulder.",
      "“That’s my family,” he explained. “I was saying goodbye before they leave.”",
      "Aurelia followed his gaze.",
      "Near the departure gates, his parents stood together with their luggage. His mother was holding a small gift bag, while his father checked the documents in his hand.",
      "Adrian looked back at Aurelia.",
      "“Are you waiting for someone too?” he asked.",
      "Aurelia glanced toward her younger self.",
      "“Yes,” she answered quietly. “I am waiting for my parents.”",
      "Adrian did not ask anything else.",
      "He only nodded, as if he understood that some answers were not ready to be spoken.",
      "The airport announcement echoed above them.",
      "Adrian adjusted the strap of his backpack.",
      "“I should go,” he said. “My mother will call me five times if I do not say goodbye properly.”",
      "Aurelia smiled.",
      "“She sounds terrifying.”",
      "“She is sweet,” Adrian replied. “That is why she is terrifying.”",
      "Aurelia laughed.",
      "Adrian stepped backward, preparing to leave.",
      "Then he looked at her again.",
      "“If you need help finding someone, the information desk is near the entrance,” he said. “Or you can stay here until they arrive.”",
      "“I will be fine,” Aurelia answered.",
      "“I know,” Adrian said. “You look like someone who always says that.”",
      "He turned toward his parents.",
      "Aurelia watched him walk away.",
      "For a moment, she forgot the machine, the unknown request, the missing return point, and the danger of standing in the past.",
      "Then the airport lights flickered.",
      "Aurelia looked toward the departure gates.",
      "Her younger self was still waiting.",
      "Adrian was still waving goodbye to his parents.",
      "And somewhere beyond the airport windows, a plane was preparing to leave."
    ]
  }
];


